name: Build and Deploy to Firebase

'on':
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Initialize Node
        uses: actions/setup-node@main
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build
        run: pip build 
      - name: Deploy
        uses: TTY-coder/firebase-action@main
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}